#!/bin/bash

usage(){
	echo "Usage: $0 COMMAND"
	echo
	echo "Commands:"
	echo "    start   Start a minecraft party!"
	echo "    save    trigger a save"
	echo "    crash   Jump into the current party (attach to the console)"
	echo "    stop    Save, stop the party and destroy the servers"
	exit 1
}

party_start() {
  terraform apply
  add_backup_cron
  add_overviewer
  party_crash
}

party_save() {
  remote_exec /bin/bash << EOF
    docker kill -s USR1 data
EOF
}

party_crash() {
  remote_exec docker attach minecraft
}

party_stop() {
  remote_exec /bin/bash << EOF
    docker stop minecraft
    docker stop --time=3600 data
EOF

  terraform plan -destroy -out=destroy.tfplan
  terraform apply destroy.tfplan
}

add_backup_cron() {
  remote_exec /bin/bash << EOF
    echo "*/10 * * * * docker kill -s USR1 data" | crontab -
EOF
}

add_overviewer() {
  remote_exec /bin/bash << EOF
    docker run -d --name=web -p 80:8000 whatupdave/partycloud-web
    crontab -l | { cat; echo "@hourly docker run --volumes-from data --volumes-from web whatupdave/partycloud-overviewer"; } | crontab -
EOF
}

remote_exec() {
  ip=`terraform show terraform.tfstate | grep ipv4_address | cut -d ' ' -f5`
  ssh -A -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@$ip $@
}

[[ $# -eq 0 ]] && usage

case "$1" in
start)
  party_start
  ;;

save)
  party_save
  ;;

crash)
  party_crash
  ;;

stop)
  party_stop
  ;;
*)
  usage
esac